MyNews/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stories.urls')),
    re_path(r'ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

stories/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'stories'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('contact-us/', views.contact_us, name= 'contact-us'),
    path('story/<int:pk>/', views.story, name= 'story'),
    path('older-children/', views.older_children, name='older-children'),
    path('young-children/', views.young_children, name='young-children'),
    path('search/', views.search_result, name='search-result'),
    path('master/', views.master, name='master'),
    path('category/<int:pk>/', views.category, name='category'),
]

stories/models.py
from django.db import models
from django.utils import timezone
import datetime
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name

class Story(models.Model):
    category = models.ForeignKey(Category, on_delete= models.PROTECT)
    name = models.CharField(max_length=200, unique=True)
    author = models.CharField(max_length=250)
    url = models.URLField(null=True)
    summary = models.TextField(null=True, blank=True)
    # content = models.TextField(blank=True)
    # content = RichTextField(blank=True)
    content = RichTextUploadingField(blank=True)
    public_day = models.DateField(default=timezone.now)
    image = models.ImageField(upload_to='stories/images', default='stories/images/logo.jpg')
    viewed = models.IntegerField(default=0)

    def __str__(self):
        return self.name
    
class Contact(models.Model):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    subject = models.CharField(max_length=200, null=True)
    message = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)

# Create your models here.

stories/forms.py
from django import forms
from .models import Contact
from django.core.validators import RegexValidator

class FormContact(forms.ModelForm):
    name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
        'placeholder': 'Enter your name',
        'class': 'form-control fh5co_contact_text_box',
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'form-control fh5co_contact_text_box',
    }))
    subject = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
        'placeholder': 'Subject',
        'class': 'form-control fh5co_contact_text_box',
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Message',
        'class': 'form-control fh5co_contact_text_message',
    }))

    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        # exclude = ['created']

stories/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from .models import *
from django.db.models import Q
from .utils import paginateStories
from .forms import FormContact


def index(request):
    stories = Story.objects.order_by('-public_day')
    most_viewed = Story.objects.order_by('viewed')[0:5]
    category = Category.objects.all()
    young_children = Category.objects.get(name='Young Children').story_set.all().order_by('-public_day')
    older_children = Category.objects.get(name='Older Children').story_set.all().order_by('-public_day')
    newest = stories[0]
    list_4_stories = stories[1:5]
    list_6 = stories[0:6]
    videos = Story.objects.filter(url__startswith='https://youtu.be/')
    context = {'category': category,'stories': stories, 'newest': newest, 'list_4_stories': list_4_stories, 'young_children': young_children, 'older_children': older_children, 'most_viewed': most_viewed, 'list_6': list_6, 'videos': videos}

    return render(request, 'stories/index.html', context)

def contact_us(request):
    # Cách 1
    # if request.POST.get('btnSend'):
    #     name = request.POST.get('name')
    #     email = request.POST.get('email')
    #     subject = request.POST.get('subject')
    #     message = request.POST.get('message')

    #     print(name)
    #     print(email)
    #     print(subject)
    #     print(message)
        
    #     contact = Contact(name=name, email=email, subject=subject, message=message)
    #     contact.save()
    
    form = FormContact()
    if request.POST.get('btnSend'):
        form = FormContact(request.POST, Contact)
        if form.is_valid():
            request.POST._mutable = True
            post = form.save(commit=False)
            post.name = form.cleaned_data['name']
            post.email = form.cleaned_data['email']
            post.subject = form.cleaned_data['subject']
            post.message = form.cleaned_data['message']
            post.save()

    stories = Story.objects.order_by('-public_day')
    most_viewed = Story.objects.order_by('viewed')[0:5]
    category = Category.objects.all()
    list_6 = stories[0:6]
    context = {'category': category, 'most_viewed': most_viewed, 'list_6': list_6, 'form': form,}
    return render(request, 'stories/contact_us.html', context)

def story(request, pk):
    stories = Story.objects.order_by('-public_day')
    most_viewed = Story.objects.order_by('viewed')[0:5]
    category = Category.objects.all()
    list_6 = stories[0:6]
    story = Story.objects.get(pk=pk)
    context = {'story': story, 'category': category, 'most_viewed': most_viewed, 'list_6': list_6}
    return render(request, 'stories/story.html', context)

def older_children(request):
    older_children = Category.objects.get(name='Older Children').story_set.all().order_by('-public_day')
    stories = Story.objects.order_by('-public_day')
    most_viewed = Story.objects.order_by('viewed')[0:5]
    category = Category.objects.all()
    list_6 = stories[0:6]
    context = {'older_children': older_children, 'category': category, 'most_viewed': most_viewed, 'list_6': list_6}
    return render(request, 'stories/older_children.html', context)

def young_children(request):
    young_children = Category.objects.get(name='Young Children').story_set.all().order_by('-public_day')
    stories = Story.objects.order_by('-public_day')
    most_viewed = Story.objects.order_by('viewed')[0:5]
    category = Category.objects.all()
    list_6 = stories[0:6]
    context = {'young_children': young_children, 'category': category, 'most_viewed': most_viewed, 'list_6': list_6}
    return render(request, 'stories/young_children.html', context)

def search_result(request):
    search_query = ""
    if request.GET.get('search_query'):
        search_query = request.GET.get('search_query').strip()

    search_result = Story.objects.distinct().filter(
        Q(category__name__icontains=search_query)|
        Q(name__icontains=search_query)|
        Q(author__icontains=search_query)|
        Q(summary__icontains=search_query)|
        Q(content__icontains=search_query)
    ).order_by('-public_day')

    search_result, custom_range = paginateStories(request, search_result, 4)
    stories = Story.objects.order_by('-public_day')
    most_viewed = Story.objects.order_by('viewed')[0:5]
    category = Category.objects.all()
    list_6 = stories[0:6]

    context = {"search_result": search_result, "search_query": search_query, 'category': category, 'most_viewed': most_viewed, 'list_6': list_6, 'custom_range': custom_range}
    return render(request, 'stories/search_result.html', context)

def category(request, pk):
    stories_filter = Story.objects.filter(category=pk).order_by('-public_day')
    stories_filter, custom_range = paginateStories(request, stories_filter, 4)
    stories = Story.objects.order_by('-public_day')
    most_viewed = Story.objects.order_by('viewed')[0:5]
    cate = Category.objects.get(pk=pk)
    category = Category.objects.all()
    list_6 = stories[0:6]
    context = {'stories_filter':stories_filter, 'stories':stories, 'category': category, 'most_viewed': most_viewed, 'list_6': list_6, 'cate': cate, 'custom_range': custom_range,}
    return render(request, 'stories/category.html', context)




def master(request):
    return render(request, 'stories/_Master.html')
# Create your views here.

stories/templates/stories/category.html
{% extends 'stories/_Master.html' %}
{% block title %}{{cate.name}} Stories{% endblock title %}
{% block content %}

<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">{{cate.name}} Stories</div>
                </div>
                {% for story in stories_filter %}
                <div class="row pb-4">
                    <div class="col-md-5">
                        <a href="{% url 'stories:story' story.pk %}">
                        <div class="fh5co_hover_news_img">
                                <div class="fh5co_news_img">
                                    <img src="{{story.image.url}}" alt="" />
                                </div>
                            <div></div>
                        </div>
                        </a>
                    </div>
                    <div class="col-md-7 animate-box">
                        <a href="{% url 'stories:story' story.pk %}" class="fh5co_magna py-2"> {{story}} </a> <a href="{% url 'stories:story' story.pk %}" class="fh5co_mini_time py-3"> {{story.author}} -
                        {{story.public_day}} </a>
                        <div class="fh5co_consectetur"> {{story.content|safe|truncatewords:20}} 
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                {% comment %} <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
                </div>
                <div class="clearfix"></div>
                <div class="fh5co_tags_all">
                    <a href="#" class="fh5co_tagg">Business</a>
                    <a href="#" class="fh5co_tagg">Technology</a>
                    <a href="#" class="fh5co_tagg">Sport</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                    <a href="#" class="fh5co_tagg">Photography</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Education</a>
                    <a href="#" class="fh5co_tagg">Social</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                </div> {% endcomment %}
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom pt-3 py-2 mb-4">Most Popular</div>
                </div>
                {% for story in most_viewed %}
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <a href="{% url 'stories:story' story.pk %}">
                            <img src="{{story.image.url}}" alt="{{story}}" class="fh5co_most_trading"/>
                        </a>
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> {{story}}</div>
                        <div class="most_fh5co_treding_font_123"> {{story.public_day}}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row mx-0">
            {% include 'stories/pagination.html' with queryset=stories_filter custom_range=custom_range %}
        </div>
    </div>
</div>
{% comment %} <div class="container-fluid pb-4 pt-5">
    <div class="container animate-box">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Most Popular</div>
        </div>
        <div class="owl-carousel owl-theme" id="slider2">
            {% for story in most_viewed %}
            <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <div class="fh5co_news_img">
                        <a href="{% url 'stories:story' story.pk %}">
                            <img src="{{story.image.url}}" alt="{{story}}"/>
                        </a>
                    </div>
                    <div>
                        <a href="{% url 'stories:story' story.pk %}" class="d-block fh5co_small_post_heading"><span class=""> {{story}}</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> {{story.author}} - {{story.public_day}}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div> {% endcomment %}
{% endblock content %}

stories/templates/stories/index.html
{% extends 'stories/_Master.html' %}
{% block title %}Home{% endblock title %}
{% block content %}

<div class="container-fluid paddding mb-5">
    <div class="row mx-0">
        <div class="col-md-6 col-12 paddding animate-box" data-animate-effect="fadeIn">
            <div class="fh5co_suceefh5co_height"><img src="{{newest.image.url}}" alt="{{newest}}"/>
                <div class="fh5co_suceefh5co_height_position_absolute"></div>
                <div class="fh5co_suceefh5co_height_position_absolute_font">
                    <div class=""><a href="{% url 'stories:story' newest.pk %}" class="color_fff"> <i class="fa fa-clock-o"></i>&nbsp;&nbsp;{{newest.public_day}}
                    </a></div>
                    <div class=""><a href="{% url 'stories:story' newest.pk %}" class="fh5co_good_font">{{newest}}</a></div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                {% for story in list_4_stories %}
                <div class="col-md-6 col-6 paddding animate-box" data-animate-effect="fadeIn">
                    <div class="fh5co_suceefh5co_height_2"><img src="{{story.image.url}}" alt="{{story}}"/>
                        <div class="fh5co_suceefh5co_height_position_absolute"></div>
                        <div class="fh5co_suceefh5co_height_position_absolute_font_2">
                            <div class=""><a href="{% url 'stories:story' story.pk %}" class="color_fff"> <i class="fa fa-clock-o"></i>&nbsp;&nbsp;{{story.public_day}}</a></div>
                            <div class=""><a href="{% url 'stories:story' story.pk %}" class="fh5co_good_font_2">{{story}}</a></div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
<div class="container-fluid pt-3">
    <div class="container animate-box" data-animate-effect="fadeIn">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Young Children ({{young_children|length}})</div>
        </div>
        <div class="owl-carousel owl-theme js" id="slider1">
            {% for story in young_children %}
            <div class="item px-2">
                <div class="fh5co_latest_trading_img_position_relative">
                    <a href="{% url 'stories:story' story.pk %}">
                        <div class="fh5co_latest_trading_img">
                            <img src="{{story.image.url}}" alt="{{story}}" class="fh5co_img_special_relative" />
                        </div>
                    </a>
                    <div class="fh5co_latest_trading_img_position_absolute"></div>
                    <div class="fh5co_latest_trading_img_position_absolute_1">
                        <a href="{% url 'stories:story' story.pk %}" class="text-white"> {{story}} </a>
                        <div class="fh5co_latest_trading_date_and_name_color"> {{story.author}} - {{story.public_day}}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="container-fluid pb-4 pt-5">
    <div class="container animate-box">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Older Children ({{older_children|length}})</div>
        </div>
        <div class="owl-carousel owl-theme" id="slider2">
            {% for story in older_children %}
            <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <a href="{% url 'stories:story' story.pk %}">
                        <div class="fh5co_news_img">
                            <img src="{{story.image.url}}" alt="{{story}}" />
                        </div>
                    </a>
                    <div>
                        <a href="{% url 'stories:story' story.pk %}" class="d-block fh5co_small_post_heading"><span class=""> {{story}}</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> {{story.author}} - {{story.public_day}}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="container-fluid fh5co_video_news_bg pb-4">
    <div class="container animate-box" data-animate-effect="fadeIn">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom pt-5 pb-2 mb-4">Story Videos</div>
        </div>
        <div>
            <div class="owl-carousel owl-theme" id="slider3">
                {% for story in videos %}
                <div class="item px-2">
                    <div class="fh5co_hover_news_img">
                        <div class="fh5co_hover_news_img_video_tag_position_relative">
                            <div class="fh5co_news_img">
                                <iframe id="video" width="100%" height="200"
                                        src="https://www.youtube.com/embed/{{story.url|slice:'17:'}}?rel=0&amp;showinfo=0"
                                        frameborder="0" allowfullscreen></iframe>
                            </div>
                            <div class="fh5co_hover_news_img_video_tag_position_absolute fh5co_hide">
                                <img src="{{story.image.url}}" alt="{{story}}"/>
                            </div>
                            <div class="fh5co_hover_news_img_video_tag_position_absolute_1 fh5co_hide" id="play-video">
                                <div class="fh5co_hover_news_img_video_tag_position_absolute_1_play_button_1">
                                    <div class="fh5co_hover_news_img_video_tag_position_absolute_1_play_button">
                                        <span><i class="fa fa-play"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pt-2">
                            <a href="{% url 'stories:story' story.pk %}" class="d-block fh5co_small_post_heading fh5co_small_post_heading_1">
                            <span class="">{{story}}</span></a>
                            <div class="c_g"><i class="fa fa-clock-o"></i> {{story.public_day}}</div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

stories/templates/stories/older_children.html
{% extends 'stories/_Master.html' %}
{% block title %}Older Children Stories{% endblock title %}
{% block content %}

<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Older Children Stories</div>
                </div>
                {% for story in older_children %}
                <div class="row pb-4">
                    <div class="col-md-5">
                        <div class="fh5co_hover_news_img">
                            <div class="fh5co_news_img">
                                <a href="{% url 'stories:story' story.pk %}">
                                    <img src="{{story.image.url}}" alt=""/>
                                </a>
                            </div>
                            <div></div>
                        </div>
                    </div>
                    <div class="col-md-7 animate-box">
                        <a href="{% url 'stories:story' story.pk %}" class="fh5co_magna py-2"> {{story}} </a> <a href="{% url 'stories:story' story.pk %}" class="fh5co_mini_time py-3"> {{story.author}} -
                        {{story.public_day}} </a>
                        <div class="fh5co_consectetur"> {{story.content|safe|truncatewords:20}} 
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                {% comment %} <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
                </div>
                <div class="clearfix"></div>
                <div class="fh5co_tags_all">
                    <a href="#" class="fh5co_tagg">Business</a>
                    <a href="#" class="fh5co_tagg">Technology</a>
                    <a href="#" class="fh5co_tagg">Sport</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                    <a href="#" class="fh5co_tagg">Photography</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Education</a>
                    <a href="#" class="fh5co_tagg">Social</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                </div> {% endcomment %}
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom pt-3 py-2 mb-4">Most Popular</div>
                </div>
                {% for story in most_viewed %}
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <a href="{% url 'stories:story' story.pk %}">
                            <img src="{{story.image.url}}" alt="{{story}}" class="fh5co_most_trading"/>
                        </a>
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> {{story}}</div>
                        <div class="most_fh5co_treding_font_123"> {{story.public_day}}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row mx-0">
            <div class="col-12 text-center pb-4 pt-4">
                <a href="#" class="btn_mange_pagging"><i class="fa fa-long-arrow-left"></i>&nbsp;&nbsp; Previous</a>
                <a href="#" class="btn_pagging">1</a>
                <a href="#" class="btn_pagging">2</a>
                <a href="#" class="btn_pagging">3</a>
                <a href="#" class="btn_pagging">...</a>
                <a href="#" class="btn_mange_pagging">Next <i class="fa fa-long-arrow-right"></i>&nbsp;&nbsp; </a>
             </div>
        </div>
    </div>
</div>
{% comment %} <div class="container-fluid pb-4 pt-5">
    <div class="container animate-box">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Most Popular</div>
        </div>
        <div class="owl-carousel owl-theme" id="slider2">
            {% for story in most_viewed %}
            <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <div class="fh5co_news_img">
                        <a href="{% url 'stories:story' story.pk %}">
                            <img src="{{story.image.url}}" alt="{{story}}"/>
                        </a>
                    </div>
                    <div>
                        <a href="{% url 'stories:story' story.pk %}" class="d-block fh5co_small_post_heading"><span class=""> {{story}}</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> {{story.author}} - {{story.public_day}}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div> {% endcomment %}
{% endblock content %}

stories/templates/stories/pagination.html
{% if queryset.has_other_pages %}
<div class="col-12 text-center pb-4 pt-4">
    <ul class="container">
        {% if queryset.has_previous %}
        <a href="?page={{queryset.previous_page_number}}" class="btn_mange_pagging"
            data-page="{{queryset.previous_page_number}}">&#10094; Prev</a>
        {% endif %}


        {% for page in custom_range %}

        {% if page == queryset.number%}
            <a href="?page={{page}}" class="btn btn_pagging active" data-page="{{page}}">{{page}}</a>
        {% else %}
            <a href="?page={{page}}" class="btn btn_pagging" data-page="{{page}}">{{page}}</a>
        {% endif %}
        {% endfor %}

        {% if queryset.has_next %}
        <a href="?page={{queryset.next_page_number}}" class="btn_mange_pagging"
            data-page="{{queryset.next_page_number}}">Next &#10095;</a>
        {% endif %}
    </ul>
</div>
{% endif %}

stories/templates/stories/story.html
{% extends 'stories/_Master.html' %}
{% block title %}{{story}}{% endblock title %}
{% block content %}

<div class="single">
    <div id="fh5co-title-box" style="background-image: url({{story.image.url}}); background-position: 50% 90.5px;"
        data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="page-title">
            <img src="{{story.image.url}}" alt="{{story}}">
            <span>{{story.public_day}}</span>
            <h2>{{story}}</h2>
        </div>
    </div>
    <div id="fh5co-single-content" class="container-fluid pb-4 pt-4 paddding">
        <div class="container paddding">
            <div class="row mx-0">
                <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                    {{story.content|safe}}
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                    {% comment %} <div>
                        <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="fh5co_tags_all">
                        <a href="#" class="fh5co_tagg">Business</a>
                        <a href="#" class="fh5co_tagg">Technology</a>
                        <a href="#" class="fh5co_tagg">Sport</a>
                        <a href="#" class="fh5co_tagg">Art</a>
                        <a href="#" class="fh5co_tagg">Lifestyle</a>
                        <a href="#" class="fh5co_tagg">Three</a>
                        <a href="#" class="fh5co_tagg">Photography</a>
                        <a href="#" class="fh5co_tagg">Lifestyle</a>
                        <a href="#" class="fh5co_tagg">Art</a>
                        <a href="#" class="fh5co_tagg">Education</a>
                        <a href="#" class="fh5co_tagg">Social</a>
                        <a href="#" class="fh5co_tagg">Three</a>
                    </div> {% endcomment %}
                    <div>
                        <div class="fh5co_heading fh5co_heading_border_bottom pt-3 py-2 mb-4">Most Popular</div>
                    </div>
                    {% for story in most_viewed %}
                    <div class="row pb-3">
                        <div class="col-5 align-self-center">
                            <a href="{% url 'stories:story' story.pk %}">
                                <img src="{{story.image.url}}" alt="{{story}}" class="fh5co_most_trading" />
                            </a>
                        </div>
                        <div class="col-7 paddding">
                            <div class="most_fh5co_treding_font"> {{story}}</div>
                            <div class="most_fh5co_treding_font_123"> {{story.public_day}}</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% comment %} <div class="container-fluid pb-4 pt-5">
        <div class="container animate-box">
            <div>
                <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Most Viewed Stories</div>
            </div>
            <div class="owl-carousel owl-theme" id="slider2">
                {% for story in most_viewed %}
                <div class="item px-2">
                    <div class="fh5co_hover_news_img">
                        <div class="fh5co_news_img">
                            <a href="{% url 'stories:story' story.pk %}">
                                <img src="{{story.image.url}}" alt="{{story}}" />
                            </a>
                        </div>
                        <div>
                            <a href="{% url 'stories:story' story.pk %}" class="d-block fh5co_small_post_heading"><span
                                    class=""> {{story}}</span></a>
                            <div class="c_g"><i class="fa fa-clock-o"></i> {{story.author}} - {{story.public_day}}</div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div> {% endcomment %}
</div>
{% endblock content %}